config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'admin/index'
  get 'welcome/search'
  post "posts/:id/comments", to: "posts#comments", as: :comments
  get 'delete', to: "admin#delete", as: :delete

  resources :posts
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :category
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @posts = Post.all
  end

  def delete
    case params[:type]
    when "post"
      Post.find(params[:id]).destroy
    when "category"
      Category.find(params[:id]).destroy
    end

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_url(@category), notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy comments ]

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  def comments
    @post.comments.create(comment_params)

    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:category_id, :title, :content, :visible)
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @posts = Post.order(created_at: :desc).limit(3)
  end

  def search
    @posts = Post
      .where("title like ?", "%#{params[:search]}%")
      .or(Post.where("content like ?", "%#{params[:search]}%"))
      .order(created_at: :desc)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

<%= link_to "Posts", posts_path %>
<%= link_to "Categories", categories_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<div class="row">
  <div class="col"><%= link_to 'New Category', new_category_path %></div>
  <div class="col"><%= link_to 'Back', admin_index_path %></div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td>
          <%= link_to 'Destroy', delete_path(id: category.id, type: 'category') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sublog</title>
    <%= csrf_meta_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Posts', categories_path %>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= collection_select(:post, :category_id, Category.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible, id: :post_visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<div class="row">
  <div class="col"><%= link_to 'New Post', new_post_path %></div>
  <div class="col"><%= link_to 'Back', admin_index_path %></div>
</div>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td><%= post.category_id %></td>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.visible %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td>
        <%= link_to 'Destroy', delete_path(id: post.id, type: 'post') %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col">
    <h1><%= @post.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col">Created: <%= @post.created_at.strftime("%d-%B-%Y") %></div>
</div>

<div class="row">
  <div class="col"><%= @post.content %></div>
</div>

<h3>Comments</h3>

<% @comments.each do |c| %>
  <p> <%= c.comment %> </p>
<% end %>

<%= form_with(model: @post.comments.new, url: comments_path(@post), local: true) do |form| %>
  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/home.html.erb
<h2>Recent Posts</h2>

<%= form_tag welcome_search_path, method: :get do %>
  <table>
    <tr>
      <td>Search:</td>
      <td><input type="text" id="search" name="search" /></td>
    </tr>
  </table>
<% end %>

<% @posts.each do |post| %>
  <strong> <%= post.title %> </strong>

  <div class="row">
    <div class="col"><%= post.content %></div>
  </div>

  <div class="row">
    <div class="col"><%= link_to "Read more >>", post %></div>
  </div>
<% end %>

app/views/welcome/search.html.erb
<h2>Search</h2>

<% @posts.each do |post| %>
  <strong> <%= post.title %> </strong>

  <div class="row">
    <div class="col"><%= post.content %></div>
  </div>

  <div class="row">
    <div class="col"><%= link_to "Read more >>", post %></div>
  </div>
<% end %>